[target.x86_64-pc-windows-gnu]
linker = "C:\\msys64\\mingw64\\bin\\gcc.exe"
ar = "C:\\msys64\\mingw64\\bin\\ar.exe"

[target.x86_64-pc-windows-msvc]
# Keep default MSVC configuration for when Visual Studio Build Tools are available
# Enable static CRT linking to eliminate VCRUNTIME140.dll dependency
rustflags = ["-C", "target-feature=+crt-static"]

[build]
# Default to GNU target when Visual Studio Build Tools are not available
# target = "x86_64-pc-windows-gnu"

[env]
# Add MinGW-w64 to PATH for build scripts
PATH = { value = "C:\\msys64\\mingw64\\bin;C:\\msys64\\usr\\bin", relative = true }

[net]
# Configure for corporate networks if needed
# git-fetch-with-cli = true

[profile.release]
# Optimize for size and performance
opt-level = 3
lto = true
codegen-units = 1
panic = "abort"
strip = "symbols"

[profile.dev]
# Faster debug builds
opt-level = 0
debug = 2
