# ZipLock Backend Configuration Sample
#
# This file demonstrates all available configuration options for the ZipLock
# backend daemon. Copy this file to your config directory and modify as needed.
#
# Default config locations:
# - Linux: ~/.config/ziplock/backend.yml
# - System: /etc/ziplock/backend.yml

ipc:
  # Unix domain socket path for IPC communication
  socket_path: "/tmp/ziplock/backend.sock"

  # Maximum number of concurrent client connections
  max_connections: 10

  # Connection timeout in seconds
  connection_timeout: 30

  # Request processing timeout in seconds
  request_timeout: 60

storage:
  # Default directory for storing archives
  default_archive_dir: "~/.local/share/ziplock"

  # Number of backup copies to maintain
  backup_count: 5

  # Enable automatic backup creation
  auto_backup: true

  # Backup directory path (defaults to archive_dir/backups if not specified)
  backup_dir: null

  # File lock timeout in seconds
  file_lock_timeout: 30

  # Enable archive integrity checking
  verify_integrity: true

  # Minimum password length for master password
  min_password_length: 12

  # 7z compression configuration
  compression:
    # Compression level (0-9, where 9 is highest compression)
    # 0 = no compression, 1 = fastest, 6 = balanced, 9 = best compression
    level: 6

    # Enable solid compression for better compression ratio
    # Note: Solid compression provides better compression but slower random access
    # to individual files. Recommended for archives that are mostly read-only.
    solid: false

  # Repository validation settings
  validation:
    # Enable comprehensive repository validation on open
    enable_comprehensive_validation: true

    # Enable deep validation (checks all credential files individually)
    deep_validation: true

    # Check for legacy format repositories and migrate them
    check_legacy_formats: true

    # Validate YAML schema compliance for all repository files
    validate_schemas: true

    # Automatically attempt to repair validation issues when found
    auto_repair: true

    # Fail repository opening if critical validation issues are found
    fail_on_critical_issues: true

    # Log detailed validation reports for monitoring and debugging
    log_validation_details: false

security:
  # Master key auto-lock timeout in seconds (0 = never auto-lock)
  auto_lock_timeout: 900 # 15 minutes

  # Master passphrase validation requirements
  passphrase_requirements:
    min_length: 12
    require_lowercase: true
    require_uppercase: true
    require_numeric: true
    require_special: true
    max_length: 0 # 0 = no limit
    min_unique_chars: 8

logging:
  # Log level: trace, debug, info, warn, error
  level: "info"

  # Enable file logging
  file_logging: false

  # Log file path (used when file_logging = true)
  log_file: null
# Example configurations for different use cases:

# High compression configuration (slower but smaller archives):
# storage:
#   compression:
#     level: 9
#     solid: true

# Fast compression configuration (faster but larger archives):
# storage:
#   compression:
#     level: 1
#     solid: false

# Development configuration (fast and permissive):
# storage:
#   backup_count: 3
#   compression:
#     level: 1
#   validation:
#     deep_validation: false
#     fail_on_critical_issues: false
#     log_validation_details: true
# security:
#   auto_lock_timeout: 0
#   passphrase_requirements:
#     min_length: 8
#     require_lowercase: false
#     require_uppercase: false
#     require_numeric: false
#     require_special: false
# logging:
#   level: "debug"
#   file_logging: true

# Production configuration (secure and robust):
# storage:
#   backup_count: 10
#   compression:
#     level: 6
#     solid: false
#   validation:
#     enable_comprehensive_validation: true
#     deep_validation: true
#     fail_on_critical_issues: true
# security:
#   auto_lock_timeout: 600  # 10 minutes
#   passphrase_requirements:
#     min_length: 16
#     require_lowercase: true
#     require_uppercase: true
#     require_numeric: true
#     require_special: true
# logging:
#   level: "warn"
#   file_logging: true
