# ZipLock Configuration File
# This is the default configuration for ZipLock password manager

# Storage settings
storage:
  # Number of backup files to keep
  backup_count: 5

  # Enable automatic backups when saving
  auto_backup: true

  # 7z compression settings
  compression:
    # Compression level (0-9, higher = better compression, slower)
    level: 6

    # Use solid compression (better compression ratio)
    solid: false

    # Enable multi-threaded compression
    multi_threaded: true

# Security settings
security:
  # Auto-lock timeout in seconds (900 = 15 minutes)
  auto_lock_timeout: 900

  # Minimum master password length
  min_master_key_length: 12

  # Enforce strong master password requirements
  enforce_strong_master_key: true

  # Clear clipboard after copying passwords (seconds)
  clipboard_clear_timeout: 30

# Backend service settings
backend:
  # Bind address for IPC communication (127.0.0.1:0 = random port)
  bind_address: "127.0.0.1:0"

  # Logging level (trace, debug, info, warn, error)
  log_level: "info"

  # Maximum number of concurrent sessions
  max_sessions: 10

  # Session timeout in seconds
  session_timeout: 3600

# User interface settings
ui:
  # Theme selection (auto, light, dark)
  theme: "auto"

  # Font size for the interface
  font_size: 14

  # Show password strength indicators
  show_password_strength: true

  # Enable search highlighting
  search_highlight: true

  # Default window size
  window:
    width: 1024
    height: 768

  # Show system tray icon
  show_tray_icon: true

# Search settings
search:
  # Enable fuzzy search
  fuzzy_search: true

  # Search in all fields by default
  search_all_fields: true

  # Maximum search results to display
  max_results: 100

# TOTP (Two-Factor Authentication) settings
totp:
  # Default time step in seconds
  time_step: 30

  # Default number of digits
  digits: 6

  # Copy TOTP codes to clipboard automatically
  auto_copy: false

# Password generator defaults
password_generator:
  # Default password length
  length: 16

  # Include uppercase letters
  uppercase: true

  # Include lowercase letters
  lowercase: true

  # Include numbers
  numbers: true

  # Include symbols
  symbols: true

  # Avoid ambiguous characters
  avoid_ambiguous: true

  # Custom symbol set (if empty, uses default)
  custom_symbols: ""

# Import/Export settings
import_export:
  # Default export format (json, csv)
  default_export_format: "json"

  # Include metadata in exports
  include_metadata: true

  # Encrypt exports by default
  encrypt_exports: true

# Logging settings
logging:
  # Enable file logging
  file_logging: true

  # Log file path (relative to user config directory)
  log_file: "ziplock.log"

  # Maximum log file size in MB
  max_log_size: 10

  # Number of log files to keep
  log_rotation_count: 5
