# ZipLock Frontend Configuration Sample
#
# This file demonstrates all available configuration options for the ZipLock
# frontend clients. Copy this file to your config directory and modify as needed.
#
# Default config locations:
# - Linux: ~/.config/ziplock/config.yml
# - Windows: %APPDATA%/ZipLock/config.yml

version: "1.0"

# Repository management settings
repository:
  # Current repository path (set automatically when opening a repository)
  path: null

  # Default directory for creating new repositories
  default_directory: "~/Documents/ZipLock"

  # Maximum number of recent repositories to remember
  max_recent: 10

  # Directories to search for repositories during discovery
  search_directories:
    - "~/Documents"
    - "~/Desktop"
    - "~/Downloads"

  # Recently opened repositories (managed automatically)
  recent_repositories: []

# User interface settings
ui:
  # Window dimensions
  window_width: 1000
  window_height: 700

  # Theme selection ("light", "dark", "system")
  theme: "system"

  # Show setup wizard on startup when no repositories are configured
  show_wizard_on_startup: true

  # Font size for UI elements
  font_size: 14.0

  # UI language/locale
  language: "en"

# Application behavior settings
app:
  # Auto-lock timeout in minutes (0 = never auto-lock)
  auto_lock_timeout: 15

  # Clipboard clear timeout in seconds (0 = never clear)
  clipboard_timeout: 30

  # Enable automatic backup creation
  enable_backup: true
# Example configurations for different use cases:

# Minimal security configuration:
# app:
#   auto_lock_timeout: 5
#   clipboard_timeout: 10
#   enable_backup: true

# Maximum convenience configuration:
# app:
#   auto_lock_timeout: 0
#   clipboard_timeout: 0
#   enable_backup: true

# Corporate/shared computer configuration:
# app:
#   auto_lock_timeout: 2
#   clipboard_timeout: 15
#   enable_backup: true
# ui:
#   show_wizard_on_startup: false
