# ZipLock Backend Configuration Example
# Copy to ~/.config/ziplock/config.yml (Linux) or %APPDATA%/ZipLock/config.yml (Windows)

# IPC Communication Settings
ipc:
  # Unix socket path for backend communication
  socket_path: "/tmp/ziplock/backend.sock"
  # Socket file permissions (octal)
  socket_permissions: 0o600
  # Maximum concurrent connections
  max_connections: 10
  # Connection timeout in seconds
  connection_timeout: 30
  # Request timeout in seconds
  request_timeout: 60
  # Log all IPC requests (for debugging)
  log_requests: false

# Storage and Archive Settings
storage:
  # Default directory for storing archives
  default_archive_dir: "~/Documents/ZipLock"
  # Maximum archive file size in MB (0 = unlimited)
  max_archive_size_mb: 500
  # Number of backup copies to maintain
  backup_count: 5
  # Enable automatic backup creation
  auto_backup: true
  # Custom backup directory (optional)
  backup_dir: null
  # File lock timeout in seconds
  file_lock_timeout: 30
  # Custom temporary directory (optional)
  temp_dir: null
  # Enable basic archive integrity checking
  verify_integrity: true
  # Minimum master password length
  min_password_length: 12

  # 7z Compression Settings
  compression:
    # Compression level (0-9, higher = better compression but slower)
    level: 6
    # Use solid compression (better compression but slower random access)
    solid: false
    # Enable multi-threaded compression
    multi_threaded: true
    # Dictionary size in MB for compression
    dictionary_size_mb: 64
    # Block size in MB (0 = auto)
    block_size_mb: 0

  # Repository Validation Settings
  validation:
    # Enable comprehensive repository validation when opening archives
    # This performs detailed checks beyond basic integrity verification
    enable_comprehensive_validation: true

    # Enable deep validation that checks all credential files individually
    # This is more thorough but takes longer for large repositories
    deep_validation: true

    # Check for legacy format repositories and automatically migrate them
    # Helps maintain compatibility with older ZipLock versions
    check_legacy_formats: true

    # Validate YAML schema compliance for all repository files
    # Ensures all files conform to the expected format specification
    validate_schemas: true

    # Automatically attempt to repair validation issues when found
    # If disabled, validation issues will only be reported but not fixed
    auto_repair: true

    # Fail repository opening if critical validation issues are found
    # When false, the repository will still open with warnings
    fail_on_critical_issues: true

    # Log detailed validation reports for monitoring and debugging
    # Useful for troubleshooting repository issues
    log_validation_details: false

# Security Settings
security:
  # Argon2 key derivation settings
  key_derivation_iterations: 3
  key_derivation_memory_kb: 65536  # 64 MB
  key_derivation_parallelism: 4

  # Auto-lock timeout in seconds (0 = disabled)
  auto_lock_timeout: 900  # 15 minutes

  # Maximum authentication attempts before lockout
  max_auth_attempts: 5
  # Lockout duration in seconds after max attempts
  auth_lockout_duration: 300  # 5 minutes

  # Enable memory protection features
  memory_protection: true
  # Clipboard clear timeout in seconds
  clipboard_clear_timeout: 30

  # Master passphrase requirements
  passphrase_requirements:
    min_length: 12
    require_lowercase: true
    require_uppercase: true
    require_numeric: true
    require_special: true
    max_length: 0  # 0 = no limit
    min_unique_chars: 8

# Logging Settings
logging:
  # Log level: trace, debug, info, warn, error
  level: "info"
  # Enable file logging
  file_logging: true
  # Log file path (defaults to system log directory)
  log_file: null
  # Maximum log file size in MB before rotation
  max_log_size_mb: 10
  # Number of rotated log files to keep
  log_rotation_count: 5
  # Use JSON format for structured logging
  json_format: false
  # Enable audit logging for security events
  audit_logging: true

# Performance and Resource Limits
limits:
  # Maximum memory usage in MB
  max_memory_mb: 512
  # Maximum cached credentials in memory
  max_cached_credentials: 1000
  # Cache TTL in seconds
  cache_ttl: 300  # 5 minutes
  # Maximum concurrent operations
  max_concurrent_operations: 10
  # Operation timeout in seconds
  operation_timeout: 120  # 2 minutes
  # Enable performance metrics collection
  enable_metrics: false

# Example Validation Profiles:
#
# For development/testing (less strict):
# validation:
#   enable_comprehensive_validation: true
#   deep_validation: false
#   check_legacy_formats: true
#   validate_schemas: false
#   auto_repair: true
#   fail_on_critical_issues: false
#   log_validation_details: true
#
# For production (strict):
# validation:
#   enable_comprehensive_validation: true
#   deep_validation: true
#   check_legacy_formats: true
#   validate_schemas: true
#   auto_repair: true
#   fail_on_critical_issues: true
#   log_validation_details: false
#
# For legacy compatibility (minimal validation):
# validation:
#   enable_comprehensive_validation: false
#   deep_validation: false
#   check_legacy_formats: true
#   validate_schemas: false
#   auto_repair: true
#   fail_on_critical_issues: false
#   log_validation_details: false
