# ZipLock Demo Configuration
# This configuration is used by the demo-validation.sh script for testing

# IPC Communication Settings
ipc:
  socket_path: "/tmp/ziplock/backend.sock"
  max_connections: 5
  connection_timeout: 30
  request_timeout: 60

# Storage and Archive Settings
storage:
  default_archive_dir: "./validation-demo"
  backup_count: 3
  auto_backup: true
  backup_dir: null
  file_lock_timeout: 30
  verify_integrity: true
  min_password_length: 8 # Relaxed for demo

  # 7z Compression Settings
  compression:
    level: 1 # Fast compression for demo
    solid: false

  # Repository Validation Settings - Configured for demo
  validation:
    enable_comprehensive_validation: true
    deep_validation: true
    check_legacy_formats: true
    validate_schemas: true
    auto_repair: true
    fail_on_critical_issues: false # Allow demo to continue
    log_validation_details: true # Detailed logging for demo

# Security Settings - Relaxed for demo
security:
  auto_lock_timeout: 0 # No auto-lock during demo
  passphrase_requirements:
    min_length: 8
    require_lowercase: false
    require_uppercase: false
    require_numeric: false
    require_special: false
    max_length: 0
    min_unique_chars: 4

# Logging Settings - Verbose for demo
logging:
  level: "debug"
  file_logging: true
  log_file: "./validation-demo/demo.log"
